## Linear Regression

Lets talk about the dataset, I have downloaded [Used Car Price Dataset](https://www.kaggle.com/datasets/rishabhkarn/used-car-dataset) from Kaggle website. The dataset contains `13` feature/independent variables($x_i$) and a target/dependant variable($y$), from those 13 feature/independant variables, I will be using 5 feature/independent variables they are `kms_driven` ,`mileage(kmpl)`, `engine(cc)`, `max_power(bhp)` and `torque(Nm). ` and `price(in lakhs)` as the target variable.<br><br>


kms_driven   | mileage(kmpl)| engine(cc) | max_power(bhp) | torque(Nm) | price(in lakhs)
-------------|-------------|------------|----------------|------------|-------------
 56000       |   7.81      |2996        |	   2996        |     333    |       63.75
 30615       |  17.4      |    999     |     999        |     9863   |       8.99
24000        |  20.68     |    1995    |     1995       |      188   |       23.75
18378        |  16.5      |    1353    |     1353       |     13808  |       13.56


<br>
<br>
Here $x$'s are four-dimensional vector in $\mathbb{R}^5$. For instance, $x_1^{(i)}$ is the `kms_driven`, $x_2^{(i)}$ is the `mileage(kmpl)`, $x_3^{(i)}$ is the `engine(cc)`, $x_4^{(i)}$ is the `max_power(bhp)`, and $x_4^{(i)}$ is the `torque(Nm)` of the $i$-th house in the training set


To perform supervised learning, we will represent $y$ as  the functions/hypothese $h$ or as a linear function of $x$.

$$h_{\theta}(x) = \theta_0 + \theta_1x_1 + \theta_2x_2 + \theta_3x_3 + \theta_4x_4 + \theta_5x_5$$

Here, the $\theta_i$'s are the parameters (also called wights) parameterizing the space of linear functions mapping $\mathcal{X}$ $\to$ $\mathcal{Y}$. For simplifying the notation, we drop $\theta$ and use $x_0=1$(intercept term).
$$h(x) = \sum_{i=0}^d\theta_ix_i = \theta^Tx$$

on the right-hand side both $\theta$ and $x$ are both vectors and d is the no. of feature/input/independent variables(not counting $x_0$).



Now, given a training set, how do we pick, or learn, the parameters $\theta$. One reasonable method is to make $h(x)$ close to $y$, atleast for the training examples we have. To formalize this, we will define a function that measures, for each value of the $\theta$'s, how close the $h(x^{(i)})$'s are to the correspoding $y^{(i)}$'s. We define the **cost function**:
$$J(\theta) = \frac{1}{2}\sum_{i=1}^n(h_{\theta}(x^{(i)})-y^{(i)})^2.$$



# LMS algorithm


We watnt to choose $\theta$ so as to minimize $J(\theta)$. To do so, let's use a search algorithm that starts with some "initial guess" for $\theta$, and that repeatedly changes $\theta$ to make $J(\theta)$ smaller, until hopefully we converge to a value of $\theta$ that minimizes $J(\theta)$. Specifically, lets consider the **gradient descent** algorithm, which starts with some initial $\theta$, and repeatedly performs the update:
$$\theta_j:=\theta_j - \alpha\frac{\partial}{\partial\theta_j}J(\theta). $$
(This update is simultaneously performed for all values of $j$= 0,...,d.)


Here, $\alpha$ is called the **learning rate**. This is a very natural algorithm that repeatedly takes a step in the direction of steepest descrease of $J$.

In order to implement this algorithm, we have to work out what is the partial derivative term on the right hand side. Lets first work it out for the case of it we have only one training example $(x, y)$, so that we can neglect the sum in the definition of $\textit{J}$. We have:


$$ \frac{\partial}{\partial\theta_j}J(\theta) = \frac{\partial}{\partial\theta_j}\frac{1}{2}(h_\theta(x) - y)^2$$
$$ = 2.\frac{1}{2}(h_\theta(x)-y).\frac{\partial}{\partial\theta_j}(h_\theta(x)-y))$$
$$=(h_\theta(x)-y).\frac{\partial}{\partial\theta_j}(\sum_{i=0}^d\theta_ix_i-y)$$
$$=(h_\theta(x)-y)x_j$$
for a single training example, this gives the update rule:
$$\theta_j:= \theta_j +\alpha(y^{(i)}-h_\theta(x^{(i)}))x_j^{(i)}. $$

This rule is called the **LMS** update rule (LMS stands for "least mean squares"), and is also known as the **Widrow-Hoff** learning rule. This rule has several properties that seem natural and intuitive. For instance, the magnitude of the update is proportial to the error term $(y^{(i)}-h_\theta(x^{(i)}))$; thus for instance, if we are encountering a training example on which our prediction nearly matches the actual value of $y^{(i)}$, then we find that there is little need to change the parameters; in contrast, a larger change to the parameters will be made if our prediction $h_\theta(x^(i)$ has a large error (i.e, if it is very far from $y^{(i)}$).

We'd derived the LMS rule for when there was only a single training example. There are two ways to modify this method for a training set of more than one example. The first is replace it with the following algorithm:

repeat until convergence $ \{ $
$$\theta_j := \theta_j + \alpha\sum_{i=i}^n(y^{(i)} - h_\theta(x^{(i)}))x_j^{(i)}, \text{(for every $j$)  (1.1)} $$
$ \}$



By grouping the updates of the coordinates into an update of the vector $\theta$, we can rewrite update (1.1) in a slightly more succing way:
$$ \theta := \theta + \alpha\sum_{i=1}^n(y^{(i)} - h_\theta(x^{(i)}))x^{(i)}$$
This is simply gradient descent on the original cost funtion $\textit{J}$. This method looks ar every example in the entire training set on every step, and is called **batch gradient descent**. Note that, while gradient descent can be susceptible to local minima in general, the optimization problem we have posed here for linear regression has only one global, and no other local, optima; thus gradient descent always converges (assumming the learning rate $\alpha$ is not too large) to the global minimum. Indeed, $\textit{J}$ is a convex quadratic funtion. Here is an examlpe of gradient descent as it run to minimize a quadratic function.

<figure>
  <img src="https://github.com/0shankart/MachineLearningNotes/blob/main/TraditionalML/images/batch_gradient_descent_global_minimum.png?raw=true" width="40%"/>
  <figcaption>Ref: https://cs229.stanford.edu/notes2021fall/cs229-notes1.pdf</figcaption>
</figure>
 <br>
 <br>The ellipses shown above are the countours of a quadratiic function. Also shown is the trajectory taken by graidnet descent, which was initialized at (48, 30). The $x$'s in the figure (joined by straight lines) mark the successive values of $\theta$ that gradient descent went through.

 There is an alternative to batch gradient descent that also works very well. Consider the folling algorithm:<br><br>$\text{Loop }  \{ $

 $ \text{ for $i$ = 1 to n, } \{ $
 $$\theta^j := \theta_j + \alpha(y^{(i)} - h_\theta(x^{(i)}))x_j^{(i)}, \text{ (for every $j$)  (1.2) }$$
 $\}$

 $\}$
<br>
By grouping the updates of the coordinates into an update of the vector \theta, we can rewrite update (1.2) in a slightly more succing way:
$$\theta := \theta + \alpha(y^{(i)} - h_\theta(x^{(i)}))x^{(i)}$$
<br>
In this algorithm, we repeatedly run through the training set, and each time we encounter a training example, we update the parameters according to the gradient of the error with respect to that single training examlpe only. This algorithm is called **stochastic gradient descent** (also **incremental gradient descent**). Whereas batch gradient descent has to scan through the entire training set before taking a single step$-$a cpst;u p[eratopm of n is large$-$stochastic gradient descent can start making progress right away and continues to ,make progress with each example it looks at. Often, stochastic gradient descent gets $\theta$ "close to the minimum much faster than batch gradient descent. (Note however that it may never "converge" to the minimum, and the parameters $\theta$ will keep oscillating around the minimum of the $J(\theta)$; but in practise most of the values near the minimum will be reasonably good approximations to the true minimum. By slowly letting the learning rate $\alpha$ decrease to zero as the algorithm runs, it is also possible to ensure that the parameters will converge to the global minimum rather than merely oscillate around the minimum.) For these reasons, particularly when the training set is large, stochastic gradient descent is often preferred voer batch gradient descent.



# Python Implementation

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd /content/drive/MyDrive/files

/content/drive/MyDrive/files


In [3]:
ls

imdb_data.csv  Used_Car_Dataset.csv  yelp.csv


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (12.0, 9.0)

In [252]:
df = pd.read_csv("Used_Car_Dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1553 entries, 0 to 1552
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          1553 non-null   int64  
 1   car_name            1553 non-null   object 
 2   registration_year   1553 non-null   object 
 3   insurance_validity  1553 non-null   object 
 4   fuel_type           1553 non-null   object 
 5   seats               1553 non-null   int64  
 6   kms_driven          1553 non-null   int64  
 7   ownsership          1553 non-null   object 
 8   transmission        1553 non-null   object 
 9   manufacturing_year  1553 non-null   object 
 10  mileage(kmpl)       1550 non-null   float64
 11  engine(cc)          1550 non-null   float64
 12  max_power(bhp)      1550 non-null   float64
 13  torque(Nm)          1549 non-null   float64
 14  price(in lakhs)     1553 non-null   float64
dtypes: float64(5), int64(3), object(7)
memory usage: 182.1+

In [253]:
# drop all other columsn except mileage(kmpl), engine(cc), max_power(bhp), torque(Nm), price(in lakhs)
# sort the dataframe based on the price(in lakhs) column and only 100 samples are choosen
df = df[:100]
df = df[['kms_driven','mileage(kmpl)', 'engine(cc)', 'max_power(bhp)', 'torque(Nm)', 'price(in lakhs)']]
df['kms_driven'] = df['kms_driven']/1000
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   kms_driven       100 non-null    float64
 1   mileage(kmpl)    100 non-null    float64
 2   engine(cc)       100 non-null    float64
 3   max_power(bhp)   100 non-null    float64
 4   torque(Nm)       100 non-null    float64
 5   price(in lakhs)  100 non-null    float64
dtypes: float64(6)
memory usage: 4.8 KB


In [254]:
# to replicate the values across, lets set the random seed
np.random.seed(seed=123456)

In [255]:
# lets create random θ vector, which is 5 dimensions
t = np.random.rand

In [256]:
# segregate the dataframe based on the

X = df[['kms_driven','mileage(kmpl)', 'engine(cc)', 'max_power(bhp)', 'torque(Nm)']].to_numpy()
y = df[['price(in lakhs)']].to_numpy()
#We then need to add a feature of “1” concatenating it with the dataset we already have and also add q to the vector m.
X = np.concatenate([X , np.ones((X.shape[0],1))], axis = 1)

In [257]:
X.shape

(100, 6)

In [258]:
X[0]

array([5.600e+01, 7.810e+00, 2.996e+03, 2.996e+03, 3.330e+02, 1.000e+00])

In [259]:
X.shape

(100, 6)

In [260]:
m = np.random.rand(5,1)

In [261]:
m.shape

(5, 1)

In [262]:
q = np.random.rand(1)
m = np.concatenate([m,q.reshape(1,-1)],axis = 0)

In [263]:
m

array([[0.12696983],
       [0.96671784],
       [0.26047601],
       [0.89723652],
       [0.37674972],
       [0.33622174]])

In [264]:
def mean_squared_error(X, y, m_stat):
    y_pred = X @ m_stat
    mse = np.sum(((y_pred - y)**2), axis = 0)/len(X)
    print(mse, "mse")
    return mse

In [265]:
def root_mean_squared_error(X, y, m_stat):
    y_pred = X @ m_stat
    rmse = (np.sum(((y_pred - y)**2), axis = 0)/len(X))**(1/2)
    print(rmse, "rmse")
    return rmse

In [267]:
def partial_derivative(X_batch, y_batch, m_stat):
    print("print")
    y_pred = X_batch @ m_stat
    print(y_pred,"y_pred")
    n = len(X_batch)

    df_dh = -(2/n) * (X_batch.T @ (y_batch - y_pred))
    df_dh = df_dh.reshape(len(df_dh), -1)
    print(df_dh, "partial")
    return df_dh

In [268]:
def training(X, y, batch_size, lr, epochs):

    for epoch in range(epochs):

        # random initial statistics
        if epoch == 0:
            m_stat = np.random.rand(X.shape[1], 1)

        # shuffle X and y using same permutation
        indices = np.arange(X.shape[0])
        np.random.shuffle(indices)

        X = X[indices]
        y = y[indices]

        # store cumulative derivative
        cumulative_derivative = np.zeros((X.shape[1], 1))
        # parti=partial_derivative(X, y, m_stat)
        # print(parti, "parti")
        # m_stat = m_stat - (lr * parti)
        # print(m_stat)
        for batch in range(len(X)//batch_size):
            start = batch*batch_size
            stop = (batch*batch_size) + batch_size

            X_batch = X[start:stop]
            y_batch = y[start:stop]
            # print(X_batch.shape, "X_batch")
            # print(y_batch.shape, "y_batch")
            #derivative
            parti = partial_derivative(X_batch, y_batch, m_stat)

            cumulative_derivative = cumulative_derivative + parti

            #updating rule
            m_stat = m_stat - (lr * cumulative_derivative)

        print(f"epoch: {epoch} ----> MSE: {root_mean_squared_error(X, y, m_stat)}")


In [270]:
batch_size = 25
lr = 0.01
epochs = 1

m_stat = training(X,y, batch_size,lr,epochs)
m_stat

print
[[ 1656.08440431]
 [11511.50666794]
 [ 3187.11665196]
 [ 1609.10205366]
 [ 6143.81649617]
 [ 3588.32161176]
 [ 1228.84399979]
 [ 9999.39214984]
 [  654.79681455]
 [ 9999.39214984]
 [ 1120.59280012]
 [ 6122.38732303]
 [ 6121.63986174]
 [ 7909.74694887]
 [ 1093.3849779 ]
 [12870.62539779]
 [17709.63819027]
 [  691.48517445]
 [ 1656.08440431]
 [11548.63035549]
 [14519.12354777]
 [ 1533.97759511]
 [ 1658.3329859 ]
 [  784.65597992]
 [  717.79101498]] y_pred
[[4.01356083e+05]
 [5.47297847e+05]
 [1.86151136e+07]
 [1.86151136e+07]
 [1.48348832e+08]
 [1.08156016e+04]] partial
print
[[-6.72233295e+08]
 [-1.56143701e+09]
 [-1.02494171e+09]
 [-3.89101940e+10]
 [-1.73834047e+10]
 [-1.56143701e+09]
 [-1.76251438e+09]
 [-1.35754174e+10]
 [-1.82632752e+10]
 [-2.09878859e+10]
 [-1.82632752e+10]
 [-2.43597736e+09]
 [-1.00707523e+09]
 [-4.71493849e+08]
 [-1.73270013e+09]
 [-1.79288011e+10]
 [-2.12232926e+09]
 [-2.29789847e+09]
 [-1.25808993e+10]
 [-1.35746873e+10]
 [-1.62733380e+10]
 [-2.11026626e